# docker-compose.yml
name: vintage-africana

services:
  db:
    image: postgres:17-alpine
    container_name: vintageafricana_db
    environment:
      POSTGRES_DB: vintage_africana
      POSTGRES_USER: vintage_africana
      POSTGRES_PASSWORD: admin111
    volumes:
      - vintageafricana_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vintage_africana -d vintage_africana"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vintageafricana_backend
    env_file:
      - ./backend/.env.docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    restart: unless-stopped
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vintageafricana_frontend
    environment:
      # Next server components can use this to build absolute URL if needed
      NEXT_PUBLIC_APP_URL: "http://localhost"
      # Next internal API proxy -> Django
      BACKEND_INTERNAL_URL: "http://backend:8000"
      NODE_ENV: "production"
    depends_on:
      - backend
    restart: unless-stopped
    expose:
      - "3000"

  nginx:
    image: nginx:1.25-alpine
    container_name: vintageafricana_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes:
  vintageafricana_db_data:
  media_volume:
  static_volume:
